# Generated by Django 5.2.11 on 2026-02-17 19:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gold_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_system', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('habit', 'Habit'), ('daily', 'Daily'), ('todo', 'Todo'), ('reward', 'Reward')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_action_at', models.DateTimeField(blank=True, help_text='Last time the primary action happened (habit increment, daily complete, todo done, reward claim).', null=True)),
                ('total_actions_count', models.PositiveIntegerField(default=0)),
                ('gold_delta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_count', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('count_increment', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('count_reset_cadence', models.CharField(blank=True, choices=[('never', 'Never'), ('day', 'Daily'), ('week', 'Weekly'), ('month', 'Monthly'), ('year', 'Yearly')], help_text="If set, habit counter can reset by cadence. 'never'/null means never resets.", max_length=10, null=True)),
                ('repeat_cadence', models.CharField(blank=True, choices=[('never', 'Never'), ('day', 'Daily'), ('week', 'Weekly'), ('month', 'Monthly'), ('year', 'Yearly')], help_text='Daily scheduling cadence. For Daily tasks, must be day/week/month/year (not never).', max_length=10, null=True)),
                ('repeat_every', models.PositiveIntegerField(default=1, help_text='Every N cadences (e.g. every 3 days, every 2 weeks).', validators=[django.core.validators.MinValueValidator(1)])),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('best_streak', models.PositiveIntegerField(default=0)),
                ('streak_goal', models.PositiveIntegerField(default=0)),
                ('last_completion_period', models.DateField(blank=True, null=True)),
                ('autocomplete_time_threshold', models.DurationField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_repeatable', models.BooleanField(default=False)),
                ('is_claimed', models.BooleanField(default=False)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claim_count', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.profile')),
                ('tags', models.ManyToManyField(blank=True, related_name='tasks', to='core.tag')),
            ],
        ),
        migrations.CreateModel(
            name='StreakBonusRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('streak_goal', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('bonus_percent', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streak_bonus_rules', to='core.task')),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(help_text='When the event occurred (can be backfilled/imported).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('daily_completed', 'DailyCompleted'), ('habit_incremented', 'HabitIncremented'), ('todo_completed', 'TodoCompleted'), ('reward_claimed', 'RewardClaimed'), ('activity_duration', 'ActivityDuration')], max_length=32)),
                ('gold_delta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('user_gold', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('count_delta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('title_snapshot', models.CharField(blank=True, max_length=200)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.profile')),
                ('reward', models.ForeignKey(blank=True, limit_choices_to=models.Q(('task_type', 'reward')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_logs', to='core.task')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='core.task')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=300)),
                ('is_completed', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='core.task')),
            ],
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(fields=('account', 'name'), name='uniq_profile_name_per_account'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['profile', 'name'], name='core_tag_profile_e24b4d_idx'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('profile', 'name'), name='uniq_tag_name_per_profile'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['profile', 'task_type', 'is_hidden'], name='core_task_profile_ce4e20_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['profile', 'due_at'], name='core_task_profile_856db0_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['profile', 'last_action_at'], name='core_task_profile_551eec_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['profile', 'created_at'], name='core_task_profile_27090b_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('task_type', 'todo'), ('is_done', False), _connector='OR'), name='task_only_todo_can_be_done'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('task_type', 'todo'), ('completed_at__isnull', True), _connector='OR'), name='task_only_todo_can_have_completed_at'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_done', False), ('completed_at__isnull', True)), models.Q(('is_done', True), ('completed_at__isnull', False)), _connector='OR'), name='task_todo_done_requires_completed_at'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('gold_delta__lt', 0), ('task_type', 'reward')), models.Q(('task_type', 'reward'), _negated=True), _connector='OR'), name='task_reward_gold_delta_negative'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('task_type', 'reward'), models.Q(('is_repeatable', False), ('is_claimed', False), ('claim_count', 0), ('claimed_at__isnull', True)), _connector='OR'), name='task_non_reward_has_default_reward_fields'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('task_type', 'reward'), _negated=True), ('is_claimed', False), ('claimed_at__isnull', False), _connector='OR'), name='task_reward_claimed_requires_claimed_at'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('task_type', 'daily'), _negated=True), models.Q(('repeat_cadence__in', ['day', 'week', 'month', 'year']), ('repeat_every__gte', 1)), _connector='OR'), name='task_daily_requires_repeat_cadence'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('task_type', 'daily'), models.Q(('repeat_cadence__isnull', True), ('current_streak', 0), ('best_streak', 0), ('streak_goal', 0), ('last_completion_period__isnull', True), ('autocomplete_time_threshold__isnull', True)), _connector='OR'), name='task_non_daily_has_default_daily_fields'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('task_type', 'habit'), models.Q(('current_count', 0), ('count_increment', 1), ('count_reset_cadence__isnull', True)), _connector='OR'), name='task_non_habit_has_default_habit_fields'),
        ),
        migrations.AddIndex(
            model_name='streakbonusrule',
            index=models.Index(fields=['task', 'streak_goal'], name='core_streak_task_id_f2447e_idx'),
        ),
        migrations.AddConstraint(
            model_name='streakbonusrule',
            constraint=models.UniqueConstraint(fields=('task', 'streak_goal'), name='uniq_bonus_rule_per_task_goal'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['profile', '-timestamp'], name='core_logent_profile_4e98d0_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['profile', 'type', '-timestamp'], name='core_logent_profile_841e99_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['profile', 'task', '-timestamp'], name='core_logent_profile_072a68_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['profile', 'reward', '-timestamp'], name='core_logent_profile_3f1174_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistitem',
            index=models.Index(fields=['task', 'sort_order'], name='core_checkl_task_id_216667_idx'),
        ),
    ]
