# Generated by Django 5.2.11 on 2026-02-26 16:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspirationalPhrase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=220, unique=True)),
                ('author', models.CharField(default='Unknown', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'created_at', 'id'],
                'indexes': [models.Index(fields=['is_active', 'sort_order', 'created_at'], name='core_inspir_is_acti_41e171_idx')],
            },
        ),
    ]
