# Generated by Django 5.2.11 on 2026-04-07 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_is_vacation_mode'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='task_non_daily_has_default_daily_fields',
        ),
        migrations.AddField(
            model_name='task',
            name='streak_protection_cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='type',
            field=models.CharField(choices=[('daily_completed', 'DailyCompleted'), ('daily_streak_protected', 'DailyStreakProtected'), ('habit_incremented', 'HabitIncremented'), ('todo_completed', 'TodoCompleted'), ('reward_claimed', 'RewardClaimed'), ('activity_duration', 'ActivityDuration')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('task_type', 'daily'), models.Q(('repeat_cadence__isnull', True), ('current_streak', 0), ('best_streak', 0), ('streak_goal', 0), ('streak_protection_cost', 1), ('last_completion_period__isnull', True), ('autocomplete_time_threshold__isnull', True)), _connector='OR'), name='task_non_daily_has_default_daily_fields'),
        ),
    ]
